---
title: "Date formatting"
author: "Gaëlle Cordier"
date: "06/11/2014"
output: html_document
---

---
##### Data frame:

```{r working directory}
act.dir<-"/home/gaelle/practicas/Coursera_Data_Science/Assessments/Reproducible_Research/"
```

```{r load data}
act.path<-file.path(act.dir, "activity.csv")
act<-read.csv(act.path, header = T, sep=",")
```

```{r data structure}
head(act)
str(act)
```

##### Original histogram with `date` as a factor:

```{r opts,echo=FALSE}
library(knitr)
opts_chunk$set(fig.width=8)
```

```{r plot ori,warning=FALSE}

library(ggplot2)

ggplot(data = act,aes(x=date,y=steps))+ 
    geom_histogram(stat="summary",fun.y="sum")+
    labs(y="",x="")+
    theme(axis.text.x=element_text(angle = 90, vjust = 0.5))
```

##### Setting `date` as a date:

```{r date format}
act2<-act
act2$date<-as.Date(act$date,format = "%Y-%m-%d")
str(act2)
```

##### Histograms with `date` as date:

```{r plots,warning=FALSE}

ggplot(data = act2,aes(x = date,y = steps))+
    geom_histogram(stat="summary",fun.y="sum")+
    labs(title="Default options\n",y="",x="")

ggplot(data = act2,aes(x = date,y = steps))+
    geom_histogram(stat="summary",fun.y="sum")+
    labs(title="Breaks = months\n",y="",x="")+    
    scale_x_date(breaks = "months")

library(scales) # to access breaks/formatting functions
    
ggplot(data = act2,aes(x = date,y = steps))+
    geom_histogram(stat="summary",fun.y="sum")+
    labs(title="Breaks = months, labels = month names\n",y="",x="")+    
    scale_x_date(breaks = "months",labels=date_format("%b"))

ggplot(data = act2,aes(x = date,y = steps))+
    geom_histogram(stat="summary",fun.y="sum")+
    labs(title="Breaks = weeks, labels = day and month name\n",y="",x="")+    
    scale_x_date(breaks = "weeks",labels=date_format("%d %b"))
```

For more examples, see: [`scale_x_date`](http://docs.ggplot2.org/current/scale_date.html)

For a complete list of the format codes, see the R help page for the `strptime` function

```{r R session info}
sessionInfo()
```
